FROM --platform=linux/amd64 node:10
WORKDIR /app

RUN npm install
RUN npm install express
RUN npm install --global mocha
RUN npm install --save request

COPY ./src /app

EXPOSE 89

CMD [ "node", "app.js" ]
